name: namer_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  firebase_database: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/temp/
    - assets/svg/
