// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfFsBnS7WXp77UK9v9e2IWj89Sa9sVON8',
    appId: '1:638932747479:web:29d307a006720bf6c41c92',
    messagingSenderId: '638932747479',
    projectId: 'socialize-994b3',
    authDomain: 'socialize-994b3.firebaseapp.com',
    storageBucket: 'socialize-994b3.appspot.com',
    measurementId: 'G-WMJRXS4YK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7irvstXuRw1xhnA6Tz-GNam_S_lDfmpI',
    appId: '1:638932747479:android:209d15621a5c7d1ac41c92',
    messagingSenderId: '638932747479',
    projectId: 'socialize-994b3',
    storageBucket: 'socialize-994b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxNSVUcUTv4cscHCFbeBsT6fCWFotxHwU',
    appId: '1:638932747479:ios:26d73ad1bd6bf66ec41c92',
    messagingSenderId: '638932747479',
    projectId: 'socialize-994b3',
    storageBucket: 'socialize-994b3.appspot.com',
    iosBundleId: 'com.example.socialize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxNSVUcUTv4cscHCFbeBsT6fCWFotxHwU',
    appId: '1:638932747479:ios:20ebf606f8a3ce2bc41c92',
    messagingSenderId: '638932747479',
    projectId: 'socialize-994b3',
    storageBucket: 'socialize-994b3.appspot.com',
    iosBundleId: 'com.example.socialize.RunnerTests',
  );
}
